### PR TITLE
Support all OSM records

### PR DESCRIPTION
**Pull request by orangejulius**
Records from OSM can (currently) be in the `address` or `venue` layer.

More importantly, in theory they could actually be in any layer, and recently [we changed the ID format](https://github.com/pelias/openstreetmap/pull/475) for OSM records so that the `source_id` (the 3rd and final component of a Pelias GID) matches exactly with the path on openstreetmap.org for a given record.

This change works well on my machine, but unfortunately I am having trouble with the vue toolchain.

Using either NPM or Yarn, I get the following error:

```
ERROR in /home/julian/repos/pelias/compare/src/views/ViewColumn.vue(124,20):
124:20 Could not find a declaration file for module 'lodash'. '/home/julian/repos/pelias/compare/node_modules/lodash/lodash.js' implicitly has an 'any' type.
  Try `npm install @types/lodash` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash';`
    122 | import { Component, Prop, Vue } from 'vue-property-decorator';
    123 | import * as L from 'leaflet';
  > 124 | import * as _ from 'lodash';
        |                    ^
    125 |
    126 | import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
    127 | import {

 ERROR  Build failed with errors.
```

@blackmad, do you have any idea what's causing this?

### CODE REVIEW

**Comment by orangejulius** [comment]
Okay, this should be all good to go now!

**Comment by blackmad** [comment]
I didn't do this because I thought there was something about like openstreetmap:polylines:xxxx that would get caught in this pattern and can't be linked. Am I wrong about that?

**Comment by orangejulius** [comment]
Oh yes, that's right! I'll update it to account for that

**Comment by blackmad** [comment]
lmk if there are changes that should be made here?

**Comment by orangejulius** [comment]
This is indeed good to merge. I just pushed a final update to the commit messages clarifying what happens with street records.

"Fortunately", polylines records are not consistent with records from the OSM importer itself and so they will not be matched by this code.

**Pull request merged**
